In [1]:
%matplotlib inline
import imp
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn

In [2]:
from problem import get_train_data

X_df, y_array = get_train_data()

In [3]:
import category_encoders as ce

In [4]:
X_toy = X_df[-100:]
y_toy = y_array[-100:]

In [25]:
cat_cols = ['Activity_code (APE)','Name','Address','City']
encoder = ce.OrdinalEncoder(cols=cat_cols)

In [26]:
encoder.fit_transform(X_toy)[cat_cols].values.shape

(100, 4)

In [72]:
encoder.transform(X_df['Activity_code (APE)']).values.shape

(1495948, 1)

In [45]:
X_toy['Activity_code (APE)'].values

array(['6820B', '6820B', '6820B', '6820B', '6820B', '3511Z', '3511Z',
       '3511Z', '3511Z', '3511Z', '4638B', '4638B', '4638B', '4638B',
       '4638B', '2529Z', '2529Z', '2529Z', '2529Z', '2529Z', '4511Z',
       '4511Z', '4511Z', '4511Z', '4511Z', '4322A', '4322A', '4322A',
       '4322A', '4322A', '4331Z', '4331Z', '4331Z', '4331Z', '4331Z',
       '4511Z', '4511Z', '4511Z', '4511Z', '4511Z', '2712Z', '2712Z',
       '2712Z', '2712Z', '2712Z', '4673B', '4673B', '4673B', '4673B',
       '6820B', '6820B', '6820B', '6820B', '6810Z', '6810Z', '6810Z',
       '6810Z', '4532Z', '4532Z', '4532Z', '4532Z', '4532Z', '4669B',
       '4669B', '4669B', '4669B', '3320C', '3320C', '3320C', '3320C',
       '3320C', '1092Z', '1092Z', '1092Z', '1092Z', '1092Z', '5510Z',
       '5510Z', '5510Z', '5510Z', '5510Z', '8219Z', '8219Z', '8219Z',
       '8219Z', '8219Z', '2562B', '2562B', '2562B', '2562B', '2562B',
       '1812Z', '1812Z', '1812Z', '1812Z', '1812Z', '2825Z', '2825Z',
       '2825Z', '2825Z'], dtype=object)

In [43]:
encoder

BackwardDifferenceEncoder(cols=1495848    6820B
1495849    6820B
1495850    6820B
1495851    6820B
1495852    6820B
1495853    3511Z
1495854    3511Z
1495855    3511Z
1495856    3511Z
1495857    3511Z
1495858    4638B
1495859    4638B
1495860    4638B
1495861    4638B
1495862    4638B
1495863    2529Z
1495864    2529Z
1495865    2529Z
1495866    2529Z
1495867    2529Z
1495868    4511Z
1495869    4511Z
1495870    4511Z
1495871    4511Z
1495872    4511Z
1495873    4322A
1495874...
1495931    8219Z
1495932    8219Z
1495933    8219Z
1495934    2562B
1495935    2562B
1495936    2562B
1495937    2562B
1495938    2562B
1495939    1812Z
1495940    1812Z
1495941    1812Z
1495942    1812Z
1495943    1812Z
1495944    2825Z
1495945    2825Z
1495946    2825Z
1495947    2825Z
Name: Activity_code (APE), Length: 100, dtype: object,
                          drop_invariant=False, handle_missing='value',
                          handle_unknown='value', mapping=None, return_df=True,
                          verbose=0)

In [3]:
X_df.head(10)

,Legal_ID,Name,Activity_code (APE),Address,Zipcode,City,Headcount,Fiscal_year_end_date,Fiscal_year_duration_in_months,Year
0,582296,COMICOB,NaN,BOULOUPARIS BP 15 BOULOUPARIS,NaN,NaN,NaN,2016-12-31,12.0,2016.0
1,582981,CIANFARANI JEAN-MICHEL,NaN,33 AVENUE H. LAFLEUR - VICTOIRE - B.P. 4031 NO...,NaN,NaN,NaN,2016-12-31,12.0,2016.0
2,588541,OK POULET 5EME SARL,NaN,23 RUE PAUL BERT,98800.0,NOUMEA,1.0,2016-12-31,12.0,2016.0
3,589275,INSTITUT DE LA QUALITE S.A.R.L.,NaN,224 RUE J. IEKAWE - COMPLEXE DE LA BELLE-VIE -...,98800.0,NOUMEA,NaN,2016-12-31,12.0,2016.0
4,592972,EXPERT TRADE,NaN,2 RUE DE L ASTROLABE OUEMO MAGENTA,98800.0,NOUMEA,NaN,2016-12-31,12.0,2016.0
5,593855,A.D.S. (ACTIVITES DE DISTRIBUTIONS ET DE SERVI...,NaN,29 RUE AMPERE DUCOS MAGENTA,98800.0,NOUMEA,NaN,2016-06-30,12.0,2016.0
6,596569,L.D.M.,NaN,LOT N? 10 - CENTRE COMMERCIAL DE LA BAIE DES C...,98800.0,NOUMEA,2.0,2016-12-31,12.0,2016.0
7,597526,SAINT YON,NaN,47 RUE JULES GARNIER,98800.0,NOUMEA,NaN,2016-12-31,12.0,2016.0
8,602672,GRAPHOPRINT,NaN,01 RUE MARTIAL DANTON - PARC D'ENTREPRISE DE L...,98800.0,NOUMEA,NaN,2016-12-31,12.0,2016.0
9,604082,EURL ARTIMON,NaN,15 RUE EDOUARD GLASSER - MOTOR POOL,98800.0,NOUMEA,NaN,2016-12-31,12.0,2016.0

In [5]:
X_toy['next_year'] = X_toy['Year']+1.

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [6]:
X_toy

,Legal_ID,Name,Activity_code (APE),Address,Zipcode,City,Headcount,Fiscal_year_end_date,Fiscal_year_duration_in_months,Year,next_year
1495848,875880106,TOUTISSUS,6820B,10 RUE SAINT SALOMON,56000.0,VANNES,NaN,2014-12-31,12.0,2014.0,2015.0
1495849,875880106,TOUTISSUS,6820B,10 RUE SAINT SALOMON,56000.0,VANNES,NaN,2015-12-31,12.0,2015.0,2016.0
1495850,875880106,TOUTISSUS,6820B,10 RUE SAINT SALOMON,56000.0,VANNES,NaN,2015-12-31,12.0,2015.0,2016.0
1495851,875880106,TOUTISSUS,6820B,10 RUE SAINT SALOMON,56000.0,VANNES,NaN,2016-12-31,12.0,2016.0,2017.0
1495852,875880106,TOUTISSUS,6820B,10 RUE SAINT SALOMON,56000.0,VANNES,NaN,2017-12-31,12.0,2017.0,2018.0
1495853,876180209,USINE HYDRO ELECTRIQUE DES FORGES DE LANOUEE,3511Z,2 RUE AIME JEGLOT,56120.0,LES FORGES,NaN,2013-09-30,12.0,2013.0,2014.0
1495854,876180209,USINE HYDRO ELECTRIQUE DES FORGES DE LANOUEE,3511Z,2 RUE AIME JEGLOT,56120.0,LES FORGES,NaN,2014-09-30,12.0,2014.0,2015.0
1495855,876180209,USINE HYDRO ELECTRIQUE DES FORGES DE LANOUEE,3511Z,2 RUE AIME JEGLOT,56120.0,LES FORGES,NaN,2015-09-30,12.0,2015.0,2016.0
1495856,876180209,USINE HYDRO ELECTRIQUE DES FORGES DE LANOUEE,3511Z,2 RUE AIME JEGLOT,56120.0,LES FORGES,1.0,2015-09-30,12.0,2015.0,2016.0
1495857,876180209,USINE HYDRO ELECTRIQUE DES FORGES DE LANOUEE,3511Z,2 RUE AIME JEGLOT,56120.0,LES FORGES,NaN,2016-09-30,12.0,2016.0,2017.0
1495858,877180257,MICHARD,4638B,IMPASSE DE LA CHAPELLE SAINT LEONARD,56450.0,THEIX NOYALO,NaN,2013-06-30,12.0,2013.0,2014.0
1495859,877180257,MICHARD,4638B,ZONE DE SAINT LEONARD SUD,56450.0,THEIX NOYALO,48.0,2014-06-30,12.0,2014.0,2015.0
1495860,877180257,MICHARD,4638B,ZONE DE SAINT LEONARD SUD,56450.0,THEIX NOYALO,48.0,2015-06-30,12.0,2015.0,2016.0
1495861,877180257,MICHARD,4638B,ZONE DE SAINT LEONARD SUD,56450.0,THEIX NOYALO,NaN,2016-06-30,12.0,2016.0,2017.0
1495862,877180257,MICHARD,4638B,IMPASSE DE LA CHAPELLE SAINT LEONARD,56450.0,THEIX NOYALO,NaN,2016-12-31,12.0,2016.0,2017.0
1495863,915450274,LE RESERVOIR,2529Z,RUE EUGENE SUE,3100.0,MONTLUCON,NaN,2013-09-30,12.0,2013.0,2014.0
1495864,915450274,LE RESERVOIR,2529Z,RUE EUGENE SUE,3100.0,MONTLUCON,68.0,2014-09-30,12.0,2014.0,2015.0
1495865,915450274,LE RESERVOIR,2529Z,RUE EUGENE SUE,3100.0,MONTLUCON,72.0,2015-09-30,12.0,2015.0,2016.0
1495866,915450274,LE RESERVOIR,2529Z,RUE EUGENE SUE,3100.0,MONTLUCON,72.0,2015-09-30,12.0,2015.0,2016.0
1495867,915450274,LE RESERVOIR,2529Z,RUE EUGENE SUE,3100.0,MONTLUCON,61.0,2016-09-30,12.0,2016.0,2017.0
1495868,915650428,GRAND GARAGE MONTLUCONNAIS,4511Z,22 RUE DE PASQUIS,3317.0,MONTLUCON,NaN,2013-12-31,12.0,2013.0,2014.0
1495869,915650428,GRAND GARAGE MONTLUCONNAIS,4511Z,22 RUE DE PASQUIS,3317.0,MONTLUCON,35.0,2014-12-31,12.0,2014.0,2015.0
1495870,915650428,GRAND GARAGE MONTLUCONNAIS,4511Z,22 RUE DE PASQUIS,3317.0,MONTLUCON,35.0,2015-12-31,12.0,2015.0,2016.0
1495871,915650428,GRAND GARAGE MONTLUCONNAIS,4511Z,22 RUE DE PASQUIS,3317.0,MONTLUCON CEDEX,35.0,2015-12-31,12.0,2015.0,2016.0
1495872,915650428,GRAND GARAGE MONTLUCONNAIS,4511Z,22 RUE DE PASQUIS,3317.0,MONTLUCON CEDEX,NaN,2016-12-31,12.0,2016.0,2017.0
1495873,915850127,ENTREPRISE PIZON ET CIE SARL,4322A,19 RUE EUGENE SUE,3100.0,MONTLUCON,NaN,2013-04-30,12.0,2013.0,2014.0
1495874,915850127,ENTREPRISE PIZON ET CIE SARL,4322A,19 RUE EUGENE SUE,3100.0,MONTLUCON,NaN,2014-04-30,12.0,2014.0,2015.0
1495875,915850127,ENTREPRISE PIZON ET CIE SARL,4322A,19 RUE EUGENE SUE,3100.0,MONTLUCON,NaN,2015-04-30,12.0,2015.0,2016.0
1495876,915850127,ENTREPRISE PIZON ET CIE SARL,4322A,35 RUE DANTON,3100.0,MONTLUCON,NaN,2015-04-30,12.0,2015.0,2016.0
1495877,915850127,ENTREPRISE PIZON ET CIE SARL,4322A,19 RUE EUGENE SUE,3100.0,MONTLUCON,NaN,2016-04-30,12.0,2016.0,2017.0
...,...,...,...,...,...,...,...,...,...,...,...
1495918,956502264,DECRIL - SERIL,3320C,RUE DE LA TUILLIERE,1700.0,MIRIBEL,7.0,2016-12-31,12.0,2016.0,2017.0
1495919,957502867,SAFE,1092Z,RUE DE SAINT BRIS,89290.0,AUGY,NaN,2013-06-30,12.0,2013.0,2014.0
1495920,957502867,SAFE,1092Z,RUE DE SAINT BRIS,89290.0,AUGY,NaN,2013-12-31,12.0,2013.0,2014.0
1495921,957502867,SAFE,1092Z,RUE DE SAINT BRIS,89290.0,AUGY,18.0,2014-12-31,12.0,2014.0,2015.0
1495922,957502867,SAFE,1092Z,RUE DE SAINT BRIS,89290.0,AUGY,NaN,2015-12-31,12.0,2015.0,2016.0
1495923,957502867,SAFE,1092Z,RUE DE SAINT BRIS,89290.0,AUGY,NaN,2016-12-31,12.0,2016.0,2017.0
1495924,958505653,GRAND HOTEL DE LA PAIX,5510Z,2 PLACE FRANCISQUE REGAUD,69002.0,LYON,0.0,2013-12-31,12.0,2013.0,2014.0
1495925,958505653,GRAND HOTEL DE LA PAIX,5510Z,2 PLACE FRANCISQUE REGAUD,69002.0,LYON,0.0,2014-12-31,12.0,2014.0,2015.0
1495926,958505653,GRAND HOTEL DE LA PAIX,5510Z,2 PLACE FRANCISQUE REGAUD,69002.0,LYON,0.0,2015-12-31,12.0,2015.0,2016.0
1495927,958505653,GRAND HOTEL DE LA PAIX,5510Z,2 PLACE FRANCISQUE REGAUD,69002.0,LYON,8.0,2015-12-31,12.0,2015.0,2016.0
1495928,958505653,GRAND HOTEL DE LA PAIX,5510Z,2 PLACE FRANCISQUE REGAUD,69002.0,LYON,0.0,2016-12-31,12.0,2016.0,2017.0
1495929,958506016,MESSAGERIES LYONNAISES DE PRESSE,8219Z,55 BOULEVARD DE LA NOIREE,38070.0,ST QUENTIN FALLAVIER,404.0,2013-12-31,12.0,2013.0,2014.0
1495930,958506016,MESSAGERIES LYONNAISES DE PRESSE,8219Z,55 BOULEVARD DE LA NOIREE,38070.0,ST QUENTIN FALLAVIER,0.0,2014-12-31,12.0,2014.0,2015.0
1495931,958506016,MESSAGERIES LYONNAISES DE PRESSE,8219Z,55 BOULEVARD DE LA NOIREE,38070.0,ST QUENTIN FALLAVIER,376.0,2014-12-31,12.0,2014.0,2015.0
1495932,958506016,MESSAGERIES LYONNAISES DE PRESSE,8219Z,55 BOULEVARD DE LA NOIREE,38070.0,ST QUENTIN FALLAVIER,0.0,2015-12-31,12.0,2015.0,2016.0
1495933,958506016,MESSAGERIES LYONNAISES DE PRESSE,8219Z,55 BOULEVARD DE LA NOIREE,38070.0,ST QUENTIN FALLAVIER,1.0,2016-12-31,12.0,2016.0,2017.0
1495934,966506057,LOIRE ETUDE,2562B,ZONE INDUSTRIELLE STELYTEC,42400.0,SAINT CHAMOND,27.0,2013-03-31,12.0,2013.0,2014.0
1495935,966506057,LOIRE ETUDE,2562B,ZONE INDUSTRIELLE STELYTEC,42400.0,SAINT CHAMOND,30.0,2013-12-31,12.0,2013.0,2014.0
1495936,966506057,LOIRE ETUDE,2562B,ZONE INDUSTRIELLE STELYTEC,42400.0,SAINT CHAMOND,NaN,2014-12-31,12.0,2014.0,2015.0
1495937,966506057,LOIRE ETUDE,2562B,ZONE INDUSTRIELLE STELYTEC,42400.0,SAINT CHAMOND,34.0,2015-12-31,12.0,2015.0,2016.0
1495938,966506057,LOIRE ETUDE,2562B,ZONE INDUSTRIELLE STELYTEC,42400.0,SAINT CHAMOND,NaN,2016-12-31,12.0,2016.0,2017.0
1495939,987320355,IBT CONCEPT,1812Z,56 CHEMIN DE SAINT BERNARD,64100.0,BAYONNE,4.0,2013-03-31,12.0,2013.0,2014.0
1495940,987320355,IBT CONCEPT,1812Z,56 CHEMIN DE SAINT BERNARD,64100.0,BAYONNE,NaN,2014-03-31,12.0,2014.0,2015.0
1495941,987320355,IBT CONCEPT,1812Z,56 CHEMIN DE SAINT BERNARD,64100.0,BAYONNE,NaN,2015-03-31,12.0,2015.0,2016.0
1495942,987320355,IBT CONCEPT,1812Z,56 CHEMIN DE SAINT BERNARD,64100.0,BAYONNE,NaN,2015-12-31,12.0,2015.0,2016.0
1495943,987320355,IBT CONCEPT,1812Z,56 CHEMIN DE SAINT BERNARD,64100.0,BAYONNE,NaN,2016-12-31,12.0,2016.0,2017.0
1495944,995750288,DAGARD,2825Z,NaN,NaN,BOUSSAC,NaN,2013-12-31,12.0,2013.0,2014.0
1495945,995750288,DAGARD,2825Z,NaN,NaN,BOUSSAC,NaN,2014-01-31,12.0,2014.0,2015.0
1495946,995750288,DAGARD,2825Z,NaN,NaN,BOUSSAC,384.0,2014-12-31,12.0,2014.0,2015.0
1495947,995750288,DAGARD,2825Z,NaN,NaN,BOUSSAC,372.0,2015-12-31,12.0,2015.0,2016.0

In [4]:
X_df.isna().sum()

Legal_ID                               0
Name                                   3
Activity_code (APE)                18390
Address                           262234
Zipcode                           251235
City                                 468
Headcount                         953576
Fiscal_year_end_date                   0
Fiscal_year_duration_in_months         0
Year                                   0
dtype: int64

In [5]:
type(X_df.isna().sum())

pandas.core.series.Series

In [9]:
X_df.shape

(1495948, 10)

In [18]:
X_df['Activity_code (APE)'].value_counts()

6420Z    79764
5610A    55947
7022Z    54970
4399C    31773
7112B    28220
6820B    27355
4520A    26693
6831Z    26294
4321A    24927
5610C    21903
9602A    21713
5510Z    21431
4332A    18994
4511Z    18709
4771Z    18631
6202A    17401
6810Z    16150
4322A    16107
4334Z    16061
6920Z    15795
7010Z    14224
3511Z    13448
1071C    13228
4941B    12808
4322B    12385
6430Z    12252
8130Z    11819
4778C    11741
6820A    11526
7111Z    10804
         ...
511R         1
322A         1
742B         1
524N         1
714B         1
7705         1
0620Z        1
205A         1
853J         1
322B         1
523C         1
192Z         1
524A         1
641C         1
221C         1
285D         1
343Z         1
518P         1
527A         1
518L         1
020B         1
6530Z        1
285C         1
452J         1
602E         1
366A         1
515H         1
281C         1
631E         1
611A         1
Name: Activity_code (APE), Length: 964, dtype: int64

In [152]:
X_df.groupby(['Name_processed','Legal_ID'])['Headcount'].agg(['mean']).isna().sum()

mean    307836
dtype: int64

In [149]:
X_df.groupby(['Legal_ID'])['Headcount'].agg(['mean']).isna().sum()

mean    306031
dtype: int64

In [153]:
X_df.groupby(['Name_processed'])['Headcount'].agg(['mean']).isna().sum()

mean    272409
dtype: int64

## Award

In [9]:
award = pd.read_csv('data/award_notices_RAMP.csv.zip', compression='zip')
award.head(3)

D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (4,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,CallID,Publication_date,End_of_call_date,Departments_of_publication,Departments_of_provision,Call_summary,Call_title,Complete_call_description,Total_amount,CPV_classes,...,ID,awarded,description,incumbent_name,incumbent_address,incumbent_zipcode,incumbent_city,incumbent_country,number_of_received_bids,amount
0,16-119770,2016-08-11 00:00:00,2016-09-20,13,NaN,mission de maitrise d'oeuvre relative aux trav...,MISSION DE MAITRISE D'OEUVRE RELATIVE AUX TRAV...,MISSION DE MAITRISE D'OEUVRE RELATIVE AUX TRAV...,NaN,71000000,...,NaN,Yes,NaN,AI PROJECT,"11, avenue de la Capelette",13010,Marseille,FR,13.0,83200.0
1,15-46335,2015-03-27 00:00:00,2015-04-25,85,85,fourniture de réactifs immunosérologiques pour...,NaN,Fourniture de réactifs immunosérologiques pour...,NaN,33696200 33696500,...,1,Yes,Kit pour recherche d'anticorps anti-IBR sur sé...,ID-VET,310 rue Louis Pasteur,34790,Grabels,FR,2.0,NaN
2,15-46335,2015-03-27 00:00:00,2015-04-25,85,85,fourniture de réactifs immunosérologiques pour...,NaN,Fourniture de réactifs immunosérologiques pour...,NaN,33696200 33696500,...,2,Yes,Kit pour recherche d'anticorps anti-IBR sur mé...,IDEXX MONTPELLIER SAS,323 RUE DE LA GALERA,34090,MONTPELLIER,FR,2.0,NaN

In [75]:
award['number_of_received_bids'].value_counts()

2.0      43029
3.0      42608
1.0      35451
4.0      31787
5.0      21534
6.0      13507
7.0       8629
8.0       5600
9.0       3963
10.0      2831
11.0      1964
12.0      1540
13.0      1111
14.0       868
15.0       758
16.0       567
17.0       421
18.0       373
20.0       316
19.0       302
21.0       269
25.0       194
22.0       193
23.0       187
24.0       181
26.0       166
29.0       134
28.0       132
27.0       121
0.0        118
         ...
202.0        1
131.0        1
288.0        1
120.0        1
220.0        1
147.0        1
187.0        1
201.0        1
197.0        1
174.0        1
134.0        1
215.0        1
191.0        1
95.0         1
111.0        1
126.0        1
152.0        1
251.0        1
301.0        1
186.0        1
727.0        1
173.0        1
104.0        1
115.0        1
103.0        1
150.0        1
156.0        1
311.0        1
155.0        1
208.0        1
Name: number_of_received_bids, Length: 175, dtype: int64

In [24]:
award.isna().sum()

CallID                             5
Publication_date                   5
End_of_call_date                 166
Departments_of_publication         5
Departments_of_provision      205148
Call_summary                       5
Call_title                    105365
Complete_call_description       1650
Total_amount                  191972
CPV_classes                    25119
Buyer_name                         5
Buyer_address                   5317
Buyer_zipcode                   7324
Buyer_city                         5
Buyer_email                    49801
Buyer_URL                      64179
Contract_awarded                   5
Lot                                0
ID                             82415
awarded                        10615
description                   155906
incumbent_name                 10626
incumbent_address              42612
incumbent_zipcode              31448
incumbent_city                 18635
incumbent_country              10626
number_of_received_bids        83162
amount                         88144
End_of_call_year                 166
dtype: int64

In [25]:
award['Name_processed'] = award['incumbent_name'].str.lower()
award['Name_processed'] = award['Name_processed'].str.replace('[^\w]','')
award['End_of_call_date'] = pd.to_datetime(award['End_of_call_date'], format='%Y-%m-%d', errors='coerce')

In [30]:
award['End_of_call_year'] = award['End_of_call_date'].dt.year
award['End_of_call_day'] = award['End_of_call_date'].dt.day
award['End_of_call_month'] = award['End_of_call_date'].dt.month

In [10]:
award['Name_processed'] = award['incumbent_name'].str.lower()
award['Name_processed'] = award['Name_processed'].str.replace('[^\w]','')
award['End_of_call_date'] = pd.to_datetime(award['End_of_call_date'], format='%Y-%m-%d', errors='coerce')
award['End_of_call_year'] = award['End_of_call_date'].dt.year
award_features = award.groupby(['Name_processed','End_of_call_year'])['amount'].agg(['count','sum'])

## Start transform

In [6]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GroupShuffleSplit

In [7]:
from sklearn.metrics import make_scorer

def loss(y_true, y_pred):
    
    if isinstance(y_true, pd.Series):
        y_true = y_true.values

    true = np.maximum(5., np.log10(np.maximum(1., y_true)))
    pred = np.maximum(5., np.log10(np.maximum(1., y_pred)))
    
    loss = np.mean(np.abs(true - pred))
    
    return loss
    
fan_loss = make_scorer(loss, greater_is_better=False)

In [8]:
def process_date(X):
    date = pd.to_datetime(X['Fiscal_year_end_date'], format='%Y-%m-%d')
    return np.c_[date.dt.year, date.dt.month, date.dt.day]

date_transformer = FunctionTransformer(process_date, validate=False)

In [13]:
process_date(X_toy).shape

(100, 3)

In [9]:
def process_APE(X):
    APE = X['Activity_code (APE)'].str[:2]
    APE2 = X['Activity_code (APE)'].str[:4]
    #APE3 = X['Activity_code (APE)'].str[2:4]
    return np.c_[pd.to_numeric(APE, errors='coerce').values,
                 pd.to_numeric(APE2, errors='coerce').values,
                 #pd.to_numeric(APE3, errors='coerce').values
                ]

APE_transformer = FunctionTransformer(process_APE, validate=False)

In [11]:
process_APE(X_toy).shape

(100, 2)

In [9]:
def zipcodes(X):
    zipcode_nums = pd.to_numeric(X['Zipcode'], errors='coerce')
    return zipcode_nums.values[:, np.newaxis]

zipcode_transformer = FunctionTransformer(zipcodes, validate=False)

In [92]:
X_toy['Activity_code (APE)'].str[-1]

1495848    B
1495849    B
1495850    B
1495851    B
1495852    B
1495853    Z
1495854    Z
1495855    Z
1495856    Z
1495857    Z
1495858    B
1495859    B
1495860    B
1495861    B
1495862    B
1495863    Z
1495864    Z
1495865    Z
1495866    Z
1495867    Z
1495868    Z
1495869    Z
1495870    Z
1495871    Z
1495872    Z
1495873    A
1495874    A
1495875    A
1495876    A
1495877    A
          ..
1495918    C
1495919    Z
1495920    Z
1495921    Z
1495922    Z
1495923    Z
1495924    Z
1495925    Z
1495926    Z
1495927    Z
1495928    Z
1495929    Z
1495930    Z
1495931    Z
1495932    Z
1495933    Z
1495934    B
1495935    B
1495936    B
1495937    B
1495938    B
1495939    Z
1495940    Z
1495941    Z
1495942    Z
1495943    Z
1495944    Z
1495945    Z
1495946    Z
1495947    Z
Name: Activity_code (APE), Length: 100, dtype: object

In [93]:
X_df['Last_APE'] = X_df['Activity_code (APE)'].str[-1]

In [10]:
def preprocess_category(X):
    cat_cols = ['Activity_code (APE)',
                #'Name',
                #'Address',
                #'City',
                #'Last_APE'
               ]
    encoder = ce.OrdinalEncoder(cols=cat_cols)
    return encoder.fit_transform(X)[cat_cols].values

category_transformer = FunctionTransformer(preprocess_category, validate=False)

In [32]:
preprocess_category(X_toy).shape

(100, 4)

In [11]:
X_df['Name_processed'] = X_df['Name'].str.lower()
X_df['Name_processed'] = X_df['Name_processed'].str.replace('[^\w]','')

In [18]:
head_cols = ['Name_processed']
head_att = ['mean',
            #'count',
           'max',
           'min',
           #'sum'
           ]
headcount_features = X_df.groupby(head_cols)['Headcount'].agg(head_att)
#headcount_features = pd.DataFrame.copy(headcount_features)
def merge_naive(X):
    df = pd.merge(X, headcount_features, left_on=head_cols, 
                  right_on=head_cols, how='left')
    return df[head_att]
merge_transformer = FunctionTransformer(merge_naive, validate=False)

In [16]:
def merge_naive2(X):
            X['Name'] = X['Name'].str.lower()     
            X['Name'] = X['Name'].str.replace('[^\w]','')
            X['Last_Year'] = X['Year'] - 1
            df = pd.merge(X, award_features, left_on=['Name','Year'], 
                          right_on=['Name_processed','End_of_call_year'], how='left')
            df2 = pd.merge(X, award_features, left_on=['Name','Last_Year'], 
                          right_on=['Name_processed','End_of_call_year'], how='left')
            return np.c_[df[['count','sum']],df2[['count','sum']]]

In [19]:
award_group = merge_naive2(X_df)

In [31]:
np.sum(np.isnan(award_group[:,2])==False)

7607

In [30]:
np.isnan(award_group[:,2])

array([ True,  True,  True, ...,  True,  True,  True])

In [78]:
award_cols = ['Name_processed',
              #'End_of_call_year'
             ]
X_award_cols = ['Name_processed',
              #    'Year'
                 ]
award_att = [
            #'mean',
            'count',
           'max',
           #'min',
           #'sum'
           ]
bid_att = [
            #'mean',
            'count',
           'max',
           #'min',
           #'sum'
           ]
award_features = award.groupby(award_cols)['amount'].agg(award_att)
bids_features = award.groupby(award_cols)['number_of_received_bids'].agg(bid_att)


def award_merge_naive(X):
    df1 = pd.merge(X, award_features, left_on=X_award_cols, 
                  right_on=award_cols, how='left')
    df2 = pd.merge(X, bids_features, left_on=X_award_cols, 
                  right_on=award_cols, how='left')
    return np.c_[df1[award_att],df1[award_att]]
award_merge_transformer = FunctionTransformer(award_merge_naive, validate=False)

In [79]:
award_merge_naive(X_df).shape

(1495948, 2)

In [14]:
numeric_transformer = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='mean'))
])

In [52]:
zipcode_col = ['Zipcode']
date_cols = ['Fiscal_year_end_date']
drop_cols = ['Name', 'Address', 'City']
APE_col = ['Activity_code (APE)']
num_cols = [
            'Legal_ID', 
            'Headcount', 
            #'Fiscal_year_duration_in_months', 
            'Year'
            ]
cat_cols = ['Activity_code (APE)',
            #'Name',
            #'Address',
            #'City',
            #'Last_APE'
            ]
merge_col = ['Legal_ID']


preprocessor_comp = ColumnTransformer(
    transformers=[
        #('zipcode', make_pipeline(zipcode_transformer, SimpleImputer(strategy='median')), zipcode_col),
        ('num', numeric_transformer, num_cols),
        #('date', make_pipeline(date_transformer, SimpleImputer(strategy='median')), date_cols),
        ('APE', make_pipeline(APE_transformer, SimpleImputer(strategy='mean')), APE_col),
        ('merge headcounts', make_pipeline(merge_transformer, SimpleImputer(strategy='mean')), head_cols),
        ('merge awards', make_pipeline(award_merge_transformer, SimpleImputer(strategy='mean')), X_award_cols),
        #('category', make_pipeline(category_transformer, SimpleImputer(strategy='median')), cat_cols)
        #('drop cols', 'drop', drop_cols),
    ])

In [185]:
preprocessor_comp.fit_transform(X_df).shape

(1495948, 5)

In [16]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=10)

In [22]:
X_df[:5]

,Legal_ID,Name,Activity_code (APE),Address,Zipcode,City,Headcount,Fiscal_year_end_date,Fiscal_year_duration_in_months,Year
0,582296,COMICOB,NaN,BOULOUPARIS BP 15 BOULOUPARIS,NaN,NaN,NaN,2016-12-31,12.0,2016.0
1,582981,CIANFARANI JEAN-MICHEL,NaN,33 AVENUE H. LAFLEUR - VICTOIRE - B.P. 4031 NO...,NaN,NaN,NaN,2016-12-31,12.0,2016.0
2,588541,OK POULET 5EME SARL,NaN,23 RUE PAUL BERT,98800.0,NOUMEA,1.0,2016-12-31,12.0,2016.0
3,589275,INSTITUT DE LA QUALITE S.A.R.L.,NaN,224 RUE J. IEKAWE - COMPLEXE DE LA BELLE-VIE -...,98800.0,NOUMEA,NaN,2016-12-31,12.0,2016.0
4,592972,EXPERT TRADE,NaN,2 RUE DE L ASTROLABE OUEMO MAGENTA,98800.0,NOUMEA,NaN,2016-12-31,12.0,2016.0

### Baseline -  RandomForestRegressor(n_estimators=10) - n_samples = 100000 - 5.170796e-01 (+/- 3.222002e-03)

In [82]:
clf = Pipeline(steps=[
    ('preprocessing', preprocessor_comp),
    ('classifier', regressor)])

cv = GroupShuffleSplit(n_splits=8, test_size=0.25)

#n_samples = 100000
n_samples = len(X_df)
scores_Xdf = -cross_val_score(clf, X_df[:n_samples], y_array[:n_samples], cv=cv, scoring=fan_loss, groups=X_df['Legal_ID'][:n_samples], n_jobs=2)

print("mean: %e (+/- %e)" % (scores_Xdf.mean(), scores_Xdf.std()))

mean: 4.101721e-01 (+/- 1.342072e-03)

In [81]:
clf = Pipeline(steps=[
    ('preprocessing', preprocessor_comp),
    ('classifier', regressor)])

cv = GroupShuffleSplit(n_splits=8, test_size=0.25)

n_samples = 100000
scores_Xdf = -cross_val_score(clf, X_df[:n_samples], y_array[:n_samples], cv=cv, scoring=fan_loss, groups=X_df['Legal_ID'][:n_samples], n_jobs=2)

print("mean: %e (+/- %e)" % (scores_Xdf.mean(), scores_Xdf.std()))

mean: 4.132015e-01 (+/- 5.568440e-03)

## Full dataset

In [84]:
clf = Pipeline(steps=[
    ('preprocessing', preprocessor_comp),
    ('classifier', regressor)])

cv = GroupShuffleSplit(n_splits=8, test_size=0.25)

#n_samples = 100000
n_samples = len(X_df)
scores_Xdf = -cross_val_score(clf, X_df[:n_samples], y_array[:n_samples], cv=cv, scoring=fan_loss, groups=X_df['Legal_ID'][:n_samples], n_jobs=2)

print("mean: %e (+/- %e)" % (scores_Xdf.mean(), scores_Xdf.std()))

D:\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning

MemoryError: could not allocate 117440512 bytes